---
title: "Fyrra R verkefni"
author: "stt27@hi.is"
date: "`r Sys.Date()`"
output: rmdformats::readthedown
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = F, message = F)
library(tidyverse)
library(knitr)
install.packages("kableExtra")
library(kableExtra)
library(lubridate)
library(dplyr)
library(ggplot2)
Sys.setlocale("LC_ALL", "Icelandic_Iceland.1252")
```


## hluti 1
Við ætlum að vinna með bla bla \n
*italic*
**Bold**

```{r}
#a
bss <- read_csv2("https://ahj.hi.is/kaupskra.csv", locale = locale(encoding = "ISO8859-1"))

#b
bss <- bss %>%
  filter(fullbuid == 1, 
         tegund %in% c("Fjolbyli", "Serbyli"),
         onothaefur_samningur == 1)

#c
bss <- bss %>%
  mutate(fermetraverd = kaupverd / einflm)

#d
bss <- bss %>%
  mutate(utgdag = as.Date(utgdag, format = "%Y-%m-%d"),
         ar = year(utgdag))

#e
bss_selected <- bss %>%
  filter(postnr %in% c(221, 200, 210))

serbyli_count <- bss_selected %>%
  filter(tegund == "Serbyli") %>%
  group_by(postnr) %>%
  summarise(fjoldi_serbyli = n())

serbyli_count %>%
  kbl(col.names = c("Póstnr.", "Fjöldi Sérbýla"), align = "c") %>%
  kable_classic_2(full_width = F)

```
## hluti 2

```{r}
#g
ggplot(bss_selected, aes(x = einflm)) +
  geom_histogram(binwidth = 10, fill = "blue", color = "black") +
  theme_minimal() +
  labs(title = "Dreifing stærða eignar",
       x = "stærð (flm)",
       y = "Magn")

#h
bss_filtered <- bss_selected %>%
  filter(tegund %in% c("Serbyli", "Fjolbyli"))

ggplot(bss_filtered, aes(x = factor(postnr), fill = tegund)) +
  geom_bar(position = "dodge") +
  theme_minimal() +
  labs(title = "Magn eigna á póstnúmer og Tegund",
       x = "Póstnúmer",
       y = "Magn",
       fill = "Tegund")

#i
ggplot(bss_selected, aes(x = factor(postnr), y = einflm)) +
  geom_boxplot() +
  theme_minimal() +
  labs(title = "eignar stærð eftir Póstnúmeri",
       x = "Póstnúmer",
       y = "Stærð")

#j
ggplot(bss_selected, aes(x = einflm, y = kaupverd, color = as.factor(ar))) +
  geom_point(alpha = 0.6) +
  facet_grid(~ postnr) +
  scale_color_viridis_d() +
  theme_minimal() +
  labs(title = "Tengsl á milli stæðar og kaupverðs eigna eftir póstnúmeri",
       x = "Stærð",
       y = "Kaupverð",
       color = "sölu ár") +
  theme(legend.position = "bottom") # Move the legend to the bottom

```

## hluti 3
```{r}
#k
property_counts <- bss_filtered %>%
  group_by(postnr, tegund) %>%
  summarise(fjoldi_eigna = n()) %>%
  ungroup()

property_counts %>%
  kbl(col.names = c("Póstnr.", "Tegund", "Fjöldi eigna"), align = "c") %>%
  kable_classic_2(full_width = F)

#l

property_type_counts <- bss_selected %>%
  filter(tegund %in% c("Serbyli", "Fjolbyli")) %>%
  count(postnr, tegund)

property_type_spread <- property_type_counts %>%
  pivot_wider(names_from = tegund, values_from = n, values_fill = list(n = 0))

property_type_proportions <- property_type_spread %>%
  mutate(
    Total = Serbyli + Fjolbyli,
    Hlutfall_Serbyli = Serbyli / Total,
    Hlutfall_Fjolbyli = Fjolbyli / Total
  ) %>%
  select(postnr, Hlutfall_Serbyli, Hlutfall_Fjolbyli)

property_type_percentages <- property_type_proportions %>%
  mutate(
    Hlutfall_Serbyli = scales::percent(Hlutfall_Serbyli),
    Hlutfall_Fjolbyli = scales::percent(Hlutfall_Fjolbyli)
  )

property_type_percentages %>%
  kbl(col.names = c("Póstnr.", "Hlutfall Sérbýli", "Fjöldi Fjölbýli"), align = "c") %>%
  kable_classic_2(full_width = F)

#m
summary_table <- bss_filtered %>%
  group_by(ar, postnr, tegund) %>%
  summarise(
    Medaltal_Fermetraverd = mean(fermetraverd, na.rm = TRUE),
    Midgildi_Fermetraverd = median(fermetraverd, na.rm = TRUE),
    Stadalfraevik_Fermetraverd = sd(fermetraverd, na.rm = TRUE),
    Fjoldi_Eigna = n()
  ) %>%
  ungroup()

summary_table %>%
  kbl(col.names = c("Ár", "Póstnr.", "Tegund", "Meðaltal Fermetraverð", "Miðgildi Fermetraverð", "Staðalfrávik Fermetraverð", "Fjöldi Eigna"), align = "c") %>%
  kable_classic_2(full_width = F)

```
## hluti 4

```{r}

```